// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN7gJQ_9g_qzIu33BKcM_xjDoxLqf__tc',
    appId: '1:633132096727:web:3b504dcddf509cc0c9a492',
    messagingSenderId: '633132096727',
    projectId: 'uptodo-e165d',
    authDomain: 'uptodo-e165d.firebaseapp.com',
    storageBucket: 'uptodo-e165d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpJhmZrbYUSYKXPwpemJy9DaaQtZGYBz4',
    appId: '1:633132096727:android:4753447a4767ace0c9a492',
    messagingSenderId: '633132096727',
    projectId: 'uptodo-e165d',
    storageBucket: 'uptodo-e165d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_HyPgC_cSbifSdJMxhM68LiyY7n_BMmY',
    appId: '1:633132096727:ios:cbac4c4717bc287ac9a492',
    messagingSenderId: '633132096727',
    projectId: 'uptodo-e165d',
    storageBucket: 'uptodo-e165d.appspot.com',
    iosBundleId: 'com.example.todoListSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_HyPgC_cSbifSdJMxhM68LiyY7n_BMmY',
    appId: '1:633132096727:ios:2a94d6459a3b104ac9a492',
    messagingSenderId: '633132096727',
    projectId: 'uptodo-e165d',
    storageBucket: 'uptodo-e165d.appspot.com',
    iosBundleId: 'com.example.todoListSample.RunnerTests',
  );
}
